name: Reassemble CSVs and Upload XLSX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.2'  # Specify the R version you need

    - name: Install R dependencies
      run: |
        R -e "install.packages('openxlsx2')"  # Add other packages if necessary

    - name: Run R script to reassemble CSVs
      run: |
        mkdir -p Data/output
        Rscript R/ICASA_DD_csv_to_xlsx.R

    - name: Debug:List files
      run: ls -lR  # List all files and directories recursively

    - name: Upload reassembled XLSX file
      uses: actions/upload-artifact@v3
      with:
        name: reassembled-xlsx
        path: Data/output/*.xlsx  # Adjust the path to the actual XLSX file location
