name: Reassemble CSVs and Upload XLSX

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write  # Add this permission for requesting the ID token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'  # Specify the R version you need

      - name: Install R dependencies
        run: |
          R -e "install.packages('openxlsx2')"  # Add other packages if necessary

      - name: List files and directories before running R script
        run: |
          echo "Listing all files and directories recursively:"
          ls -lR
          echo "Checking the contents of the root directory:"
          ls -lR .
          echo "Checking the contents of the R directory:"
          ls -lR R
          echo "Checking the contents of the Data directory:"
          ls -l Data
          
      - name: R script is called
        run: |
          Rscript -e 'source("R/ICASA_DD_csv_to_xlsx.R")'
          
      - name: Debug:List files post script
        run: |
          echo "Listing all files and directories recursively after script:"
          ls -lR
          echo "Checking the contents of Data directory:"
          ls -l Data

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Combined_CSVs.xlsx
          git commit -m "Add reassembled XLSX file"

          # Authenticate git with the Actions OIDC token
          echo ::add-mask::$ACTIONS_ID_TOKEN_REQUEST_TOKEN
          http_status_code=$(curl -s -H "Authorization: token $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -X POST -d '{"audience": "github.com"}' \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.status_code')

          if [[ "$http_status_code" != 200 ]]; then
              echo "Error authenticating with OIDC: $http_status_code"
              exit 1
          fi

          id_token=$(curl -s -H "Authorization: token $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            -X POST -d '{"audience": "github.com"}' \
            "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')

          git push https://x-access-token:$id_token@github.com/${{ github.repository }}.git HEAD:main

      - name: Upload reassembled XLSX file (optional, in case you still want to keep it as an artifact)
        uses: actions/upload-artifact@v4
        with:
          name: reassembled-xlsx
          path: Combined_CSVs.xlsx
